service: shopee

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  memorySize: 256
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
  stage: ${env:NODE_ENV}
  environment:
    SHOPEE_URL: ${env:SHOPEE_URL}
  
functions:
  hello:
    handler: dist/src/handlers/index.hello
    events:
      - http:
          method: GET
          path: /hello
          authorizer:
            arn: ${env:COGNITO_ARN}
            scopes:
              - ${env:COGNITO_SCOPES}

  searchproducts:
    handler: dist/src/handlers/index.searchproducts
    events:
      - http:
          method: GET
          path: /products
          request:
            parameters:
              querystrings:
                product: true
          authorizer:
            arn: ${env:COGNITO_ARN}
            scopes:
              - ${env:COGNITO_SCOPES}

custom:
  serverless-offline:
    httpPort: 4100
    websocketPort: 4101
    lambdaPort: 4102
  bundle:
    linting: false

plugins:
  - serverless-offline
